WITH DATE_SAEL AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
),
BOOK_DATE_SAEL AS (
    SELECT AUTHOR_ID, CATEGORY, PRICE * SALES AS BOOK_TOTAL_SALE
    FROM BOOK LEFT JOIN DATE_SAEL
    ON BOOK.BOOK_ID = DATE_SAEL.BOOK_ID
)

SELECT BDS.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK_TOTAL_SALE) AS TOTAL_SALES
FROM BOOK_DATE_SAEL AS BDS LEFT JOIN AUTHOR AS A
ON BDS.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

