SELECT ECOLI_DATA.ID, COALESCE(COUNT_DATA.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
                           FROM ECOLI_DATA
                           GROUP BY PARENT_ID) AS COUNT_DATA
ON ECOLI_DATA.ID = COUNT_DATA.PARENT_ID