WITH USE_TABLE AS (
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' && END_DATE >= '2022-10-16'
    ORDER BY CAR_ID 
)

SELECT CR.CAR_ID, COALESCE(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CR LEFT JOIN USE_TABLE AS UT
ON CR.CAR_ID = UT.CAR_ID
GROUP BY CR.CAR_ID
ORDER BY CR.CAR_ID DESC