WITH CATE_MAX AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT FP.CATEGORY, CM.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP JOIN CATE_MAX AS CM
WHERE CM.MAX_PRICE = FP.PRICE AND CM.CATEGORY = FP.CATEGORY
ORDER BY CM.MAX_PRICE DESC